defaults {
    max_fds 8192
    queue_without_daemon no
    user_friendly_names no
}

devices {
    device {
        vendor "NFINIDAT"
        product "InfiniBox.*"
        path_grouping_policy "group_by_prio"
        path_checker "tur"
        features "0"
        hardware_handler "1 alua"
        prio "alua"
        rr_weight "priorities"
        no_path_retry "queue"
        rr_min_io 1
        rr_min_io_rq 1
        flush_on_last_del "yes"
        fast_io_fail_tmo 15
        dev_loss_tmo "infinity"	
        path_selector "round-robin 0"
        failback immediate
        detect_prio yes
    }
}
