defaults {
    max_fds "max"
    find_multipaths "yes"
}

devices {
    device {
        vendor "NFINIDAT"
        product "InfiniBox"
        path_grouping_policy "group_by_prio"
        path_checker "tur"
        features "0"
        hardware_handler "1 alua"
        prio "alua"
        rr_weight "priorities"
        no_path_retry "queue"
        rr_min_io 1
        rr_min_io_rq 1
        flush_on_last_del "yes"
        fast_io_fail_tmo 15
        dev_loss_tmo "infinity"	
        path_selector "service-time 0"
        failback immediate
        detect_prio "no"
        user_friendly_names "no"
    }
}
